# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Titre
title: PAPS
tagline: Partage Autour de la Psychomotricité au Sénégal

# Site logo
logo: /images/logo.png

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  Association PAPS - Partage Autour de la Psychomotricité au Sénégal. Nous développons la psychomotricité au Sénégal à travers des missions, formations et partenariats locaux.

# SEO and Social Media Configuration
lang: fr_FR
locale: fr_FR
timezone: Europe/Paris

# Social media and SEO
twitter:
  username: assopaps
  card: summary_large_image

facebook:
  app_id: 
  publisher: https://www.facebook.com/assopaps
  admins: 

# Google Analytics (add your tracking ID when available)
# google_analytics: UA-XXXXXXXX-X

# Search Console verification (add when you set up Google Search Console)
# google_site_verification: 

# Organization schema markup
organization:
  name: "PAPS - Partage Autour de la Psychomotricité au Sénégal"
  url: "https://assopaps.github.io/paps"
  logo: "https://assopaps.github.io/paps/images/logo.png"
  sameAs:
    - "https://www.facebook.com/assopaps"
    - "https://www.instagram.com/assopaps"
    - "https://www.linkedin.com/company/assopaps"
  

# Site URL configuration for GitHub Pages
url: "https://assopaps.github.io"
baseurl: "/paps"

# Repository URL
repourl: "https://assopaps.github.io/paps"

sass:
  sass_dir: _sass

# Site navigation
navigation:
- text: Accueil
  url: /
- text: Qui Sommes-Nous ? # Notre association + Quest ce que la psychmotricite
  url: /qui-sommes-nous/
- text: Nos projets
  url: /nos-projets/
- text: Nos actus
  url: /nos-actus/
- text: Nous soutenir
  url: /nous-soutenir/
- text: Contact
  url: /contact/

# Info perso (inutilisée)
author_name:
author_bio:
author_url:
author_location:
author_image: 

# Footer (inutilisée)
banner_image: 
banner_url: 

# Footer url mailchimp pour forms (inutilisée)
mailchimp_url:

# Liens réseaux sociaux
# twitter_username: "username"
facebook_username: "assopaps"
github_username: "assopaps"
#codepen_username: "username"
#dribbble_username: "username"
#medium_username: "@username"
instagram_username: "assopaps"
#pinterest_username: "username"
linkedin_username: "assopaps"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/nos-projets/page:num/'
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
